#:schema node_modules/wrangler/config-schema.json
name = "timo-limo"
compatibility_date = "2024-09-25"
compatibility_flags = ["nodejs_compat"]

# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "timo-limo-2025-09"
database_id = "59137a04-665c-4f09-a0e6-3bb456994a72"

# R2 Bucket
[[r2_buckets]]
binding = "R2"
bucket_name = "timo-limo-2025-09"

# Environment Variables
[vars]
NEXT_PUBLIC_APP_URL = "https://timo-limo.pages.dev"
MAX_FILE_SIZE = "52428800"
ALLOWED_ORIGINS = "https://timo-limo.pages.dev"

# Pages build configuration
pages_build_output_dir = ".vercel/output/static"
