name = "timo-limo"
compatibility_date = "2025-09-01"
compatibility_flags = [ "nodejs_compat_v2" ]
pages_build_output_dir = ".vercel/output/static"

# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "timo-limo-2025-09"
database_id = "59137a04-665c-4f09-a0e6-3bb456994a72"

# R2 Bucket
[[r2_buckets]]
binding = "R2"
bucket_name = "timo-limo-2025-09"

# Environment Variables
[vars]
NEXT_PUBLIC_APP_URL = "https://timo.limo"
MAX_FILE_SIZE = "52428800"
ALLOWED_ORIGINS = "https://timo.limo"
R2_PUBLIC_URL = "https://assets.timo.limo"
